import base from '@opd/config/eslint';

export default [
  // Generated by `next build` - not ours to lint or edit.
  { ignores: ['next-env.d.ts', '.next/**'] },
  ...base,
  {
    // The console walkthrough is a Node script, not part of the bundle: it talks to
    // a running server and prints what it found. Globals listed by hand rather than
    // pulling in `globals` for a handful of names.
    files: ['test/**/*.mjs'],
    languageOptions: {
      globals: {
        AbortSignal: 'readonly',
        Buffer: 'readonly',
        FormData: 'readonly',
        URL: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        process: 'readonly',
        setTimeout: 'readonly',
      },
    },
    rules: { 'no-console': 'off' },
  },
];
